# Generated by Django 3.2.6 on 2021-09-16 20:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='uid',
            field=models.TextField(default=uuid.uuid4, max_length=40),
        ),
    ]
